version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/bitbucket.org/zurichess/board
    steps:
      - checkout
      - run:
          name: Build
          command: go build ./...
      - run:
          name: Test
          command: go test ./...
      - run:
          name: Vet
          command: go vet ./...
