// Copyright 2014-2016 The Zurichess Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// generated by stringer -type Figure; DO NOT EDIT

package board

import "fmt"

const _Figure_name = "NoFigurePawnKnightBishopRookQueenKing"

var _Figure_index = [...]uint8{0, 8, 12, 18, 24, 28, 33, 37}

func (i Figure) String() string {
	if i >= Figure(len(_Figure_index)-1) {
		return fmt.Sprintf("Figure(%d)", i)
	}
	return _Figure_name[_Figure_index[i]:_Figure_index[i+1]]
}
