// Copyright 2014-2016 The Zurichess Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// generated by stringer -type MoveType; DO NOT EDIT

package board

import "fmt"

const _MoveType_name = "NoMoveNormalPromotionCastlingEnpassant"

var _MoveType_index = [...]uint8{0, 6, 12, 21, 29, 38}

func (i MoveType) String() string {
	if i >= MoveType(len(_MoveType_index)-1) {
		return fmt.Sprintf("MoveType(%d)", i)
	}
	return _MoveType_name[_MoveType_index[i]:_MoveType_index[i+1]]
}
